// Copyright (c) 2014, Tamas Csala

#ifndef OGLWRAP_ENUMS_COLOR_BUFFER_H_
#define OGLWRAP_ENUMS_COLOR_BUFFER_H_

#include "../config.h"

namespace oglwrap {

inline namespace enums {

enum class ColorBuffer : GLenum {
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_NONE)
  None = GL_NONE,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_FRONT_LEFT)
  FrontLeft = GL_FRONT_LEFT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_FRONT_RIGHT)
  FrontRight = GL_FRONT_RIGHT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_BACK_LEFT)
  BackLeft = GL_BACK_LEFT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_BACK_RIGHT)
  BackRight = GL_BACK_RIGHT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_FRONT)
  Front = GL_FRONT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_BACK)
  Back = GL_BACK,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_LEFT)
  Left = GL_LEFT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RIGHT)
  Right = GL_RIGHT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_FRONT_AND_BACK)
  FrontAndBack = GL_FRONT_AND_BACK,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT0)
  Color0 = GL_COLOR_ATTACHMENT0,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT1)
  Color1 = GL_COLOR_ATTACHMENT1,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT2)
  Color2 = GL_COLOR_ATTACHMENT2,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT3)
  Color3 = GL_COLOR_ATTACHMENT3,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT4)
  Color4 = GL_COLOR_ATTACHMENT4,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT5)
  Color5 = GL_COLOR_ATTACHMENT5,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT6)
  Color6 = GL_COLOR_ATTACHMENT6,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT7)
  Color7 = GL_COLOR_ATTACHMENT7,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT8)
  Color8 = GL_COLOR_ATTACHMENT8,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT9)
  Color9 = GL_COLOR_ATTACHMENT9,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT10)
  Color10 = GL_COLOR_ATTACHMENT10,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT11)
  Color11 = GL_COLOR_ATTACHMENT11,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT12)
  Color12 = GL_COLOR_ATTACHMENT12,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT13)
  Color13 = GL_COLOR_ATTACHMENT13,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT14)
  Color14 = GL_COLOR_ATTACHMENT14,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COLOR_ATTACHMENT15)
  Color15 = GL_COLOR_ATTACHMENT15,
#endif
};

} // enums

} // oglwrap

#endif
