// Copyright (c) 2014, Tamas Csala

#ifndef OGLWRAP_ENUMS_MEMORY_BARRIER_BIT_H_
#define OGLWRAP_ENUMS_MEMORY_BARRIER_BIT_H_

#include "../config.h"

namespace oglwrap {

inline namespace enums {

enum class MemoryBarrierBit : GLenum {
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT)
  VertexAttribArrayBarrierBit = GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_ELEMENT_ARRAY_BARRIER_BIT)
  ElementArrayBarrierBit = GL_ELEMENT_ARRAY_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_UNIFORM_BARRIER_BIT)
  UniformBarrierBit = GL_UNIFORM_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_TEXTURE_FETCH_BARRIER_BIT)
  TextureFetchBarrierBit = GL_TEXTURE_FETCH_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_SHADER_IMAGE_ACCESS_BARRIER_BIT)
  ShaderImageAccessBarrierBit = GL_SHADER_IMAGE_ACCESS_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMMAND_BARRIER_BIT)
  CommandBarrierBit = GL_COMMAND_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_PIXEL_BUFFER_BARRIER_BIT)
  PixelBufferBarrierBit = GL_PIXEL_BUFFER_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_TEXTURE_UPDATE_BARRIER_BIT)
  TextureUpdateBarrierBit = GL_TEXTURE_UPDATE_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_BUFFER_UPDATE_BARRIER_BIT)
  BufferUpdateBarrierBit = GL_BUFFER_UPDATE_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_FRAMEBUFFER_BARRIER_BIT)
  FramebufferBarrierBit = GL_FRAMEBUFFER_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_TRANSFORM_FEEDBACK_BARRIER_BIT)
  TransformFeedbackBarrierBit = GL_TRANSFORM_FEEDBACK_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_ATOMIC_COUNTER_BARRIER_BIT)
  AtomicCounterBarrierBit = GL_ATOMIC_COUNTER_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_SHADER_STORAGE_BARRIER_BIT)
  ShaderStorageBarrierBit = GL_SHADER_STORAGE_BARRIER_BIT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT)
  ClientMappedBufferBarrierBit = GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT,
#endif
};

} // enums

} // oglwrap

#endif
