// Copyright (c) 2014, Tamas Csala

#ifndef OGLWRAP_ENUMS_PIXEL_DATA_INTERNAL_FORMAT_H_
#define OGLWRAP_ENUMS_PIXEL_DATA_INTERNAL_FORMAT_H_

#include "../config.h"

namespace oglwrap {

inline namespace enums {

enum class PixelDataInternalFormat : GLenum {
// Base internal
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_DEPTH_COMPONENT)
  DepthComponent = GL_DEPTH_COMPONENT,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_DEPTH_STENCIL)
  DepthStencil = GL_DEPTH_STENCIL,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RED)
  Red = GL_RED,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG)
  RG = GL_RG,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB)
  RGB = GL_RGB,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA)
  RGBA = GL_RGBA,
#endif

// Sized Internal
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R8)
  R8 = GL_R8,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R8_SNORM)
  R8_SNorm = GL_R8_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R16)
  R16 = GL_R16,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R16_SNORM)
  R16_SNorm = GL_R16_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG8)
  RG8 = GL_RG8,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG8_SNORM)
  RG8_SNorm = GL_RG8_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG16)
  RG16 = GL_RG16,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG16_SNORM)
  RG16_SNorm = GL_RG16_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R3_G3_B2)
  R3_G3_B2 = GL_R3_G3_B2,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB4)
  RGB4 = GL_RGB4,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB5)
  RGB5 = GL_RGB5,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB8)
  RGB8 = GL_RGB8,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB8_SNORM)
  RGB8_SNorm = GL_RGB8_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB10)
  RGB10 = GL_RGB10,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB12)
  RGB12 = GL_RGB12,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB16)
  RGB16 = GL_RGB16,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB16_SNORM)
  RGB16_SNorm = GL_RGB16_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA2)
  RGBA2 = GL_RGBA2,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA4)
  RGBA4 = GL_RGBA4,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB5_A1)
  RGB5A1 = GL_RGB5_A1,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA8)
  RGBA8 = GL_RGBA8,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA8_SNORM)
  RGBA8_SNorm = GL_RGBA8_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB10_A2)
  RGB10_A2 = GL_RGB10_A2,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB10_A2UI)
  RGB10_A2UI = GL_RGB10_A2UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA12)
  RGBA12 = GL_RGBA12,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA16)
  RGBA16 = GL_RGBA16,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA16_SNORM)
  RGBA16_SNorm = GL_RGBA16_SNORM,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_SRGB8)
  SRGB8 = GL_SRGB8,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_SRGB8_ALPHA8)
  SRGBA8 = GL_SRGB8_ALPHA8,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R16F)
  R16F = GL_R16F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG16F)
  RG16F = GL_RG16F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB16F)
  RGB16F = GL_RGB16F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA16F)
  RGBA16F = GL_RGBA16F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R32F)
  R32F = GL_R32F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG32F)
  RG32F = GL_RG32F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB32F)
  RGB32F = GL_RGB32F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA32F)
  RGBA32F = GL_RGBA32F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R11F_G11F_B10F)
  R11F_G11F_B10F = GL_R11F_G11F_B10F,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB9_E5)
  RGB9_E5 = GL_RGB9_E5,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R8I)
  R8I = GL_R8I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R8UI)
  R8UI = GL_R8UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R16I)
  R16I = GL_R16I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R16UI)
  R16UI = GL_R16UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R32I)
  R32I = GL_R32I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_R32UI)
  R32UI = GL_R32UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG8I)
  RG8I = GL_RG8I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG8UI)
  RG8UI = GL_RG8UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG16I)
  RG16I = GL_RG16I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG16UI)
  RG16UI = GL_RG16UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG32I)
  RG32I = GL_RG32I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RG32UI)
  RG32UI = GL_RG32UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB8I)
  RGB8I = GL_RGB8I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB8UI)
  RGB8UI = GL_RGB8UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB16I)
  RGB16I = GL_RGB16I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB16UI)
  RGB16UI = GL_RGB16UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB32I)
  RGB32I = GL_RGB32I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGB32UI)
  RGB32UI = GL_RGB32UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA8I)
  RGBA8I = GL_RGBA8I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA8UI)
  RGBA8UI = GL_RGBA8UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA16I)
  RGBA16I = GL_RGBA16I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA16UI)
  RGBA16UI = GL_RGBA16UI,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA32I)
  RGBA32I = GL_RGBA32I,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_RGBA32UI)
  RGBA32UI = GL_RGBA32UI,
#endif

// Compressed
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_RED)
  Compressed_Red = GL_COMPRESSED_RED,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_RG)
  Compressed_RG = GL_COMPRESSED_RG,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_RGB)
  Compressed_RGB = GL_COMPRESSED_RGB,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_RGBA)
  Compressed_RGBA = GL_COMPRESSED_RGBA,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_SRGB)
  Compressed_SRGB = GL_COMPRESSED_SRGB,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_SRGB_ALPHA)
  Compressed_SRGBA = GL_COMPRESSED_SRGB_ALPHA,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_RED_RGTC1)
  Compressed_Red_RGTC1 = GL_COMPRESSED_RED_RGTC1,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_SIGNED_RED_RGTC1)
  Compressed_Signed_Red_RGTC1 = GL_COMPRESSED_SIGNED_RED_RGTC1,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_RG_RGTC2)
  Compressed_RG_RGTC2 = GL_COMPRESSED_RG_RGTC2,
#endif
#if OGLWRAP_DEFINE_EVERYTHING || defined(GL_COMPRESSED_SIGNED_RG_RGTC2)
  Compressed_Signed_RG_RGTC2 = GL_COMPRESSED_SIGNED_RG_RGTC2,
#endif
};

} // enums

} // oglwrap

#endif
